# user-service
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: Handles user account management.
  annotations:
    github.com/project-slug: Jagpreet153/github-actions
spec:
  type: service
  owner: Jagpreet153
  lifecycle: production
  providesApis:
    - user-api

---
# order-service
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  description: Handles order management and checkout.
  annotations:
    github.com/project-slug: your-org/order-service
spec:
  type: service
  owner: github-actions
  lifecycle: production
  providesApis:
    - order-api
