# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-service
  description: A demo service with GitHub Actions workflow
  annotations:
    github.com/project-slug: Jagpreet153/github-actions
spec:
  type: service
  lifecycle: experimental
  owner: Jagpreet153