name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello World"
        shell: bash

  goodbye:
    runs-on: windows-latest
    steps:
      - name: Goodbye World
        run: echo "Goodbye World"
        shell: bash
