name: Create a comment on issue

on: 
  issues: 
   types: [-opened]

jobs: 
 comment-with-action:
   runs-on: ubnutu-latest
   steps: 
    - name: "dump github context"
      run: echo '${{ toJSON(github.event) }}' jq
      shell: bash
